global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'voltdb'
    static_configs:
      - targets: [ 'voltdb:11781' ]
        labels:
          namespace: 'dev-edition'
  - job_name: 'voltsp'
    static_configs:
      - targets: [ 'voltsp:11781' ]
        labels:
          namespace: 'dev-edition'
